[build]
  functions = "functions"

[dev]
  publish = "dist"

[[redirects]]
  for="/*"
  to="/.netlify/functions/api"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
