[build]
  functions = "functions"

[dev]
  publish = "dist"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/api/staff/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/.netlify/functions/api/draft/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
